#!/usr/bin/env dart
/*
Скрипт на Dart для автоматического получения реальных скриншотов через Steam API.
Запуск: dart fetch_steam_screenshots.dart

Steam Store API endpoint: https://store.steampowered.com/api/appdetails?appids={appid}
*/

import 'dart:convert';
import 'dart:io';

const String steamApiUrl = "https://store.steampowered.com/api/appdetails";
const String steamCdnUrl = "https://cdn.cloudflare.steamstatic.com";

/// Получает детали игры из Steam Store API
Future<Map<String, dynamic>?> fetchGameDetails(int appid) async {
  final url = Uri.parse("$steamApiUrl?appids=$appid");
  
  try {
    final client = HttpClient();
    client.userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36";
    
    final request = await client.getUrl(url);
    final response = await request.close();
    
    if (response.statusCode == 200) {
      final body = await response.transform(utf8.decoder).join();
      final data = jsonDecode(body);
      
      if (data[appid.toString()] != null && data[appid.toString()]['success'] == true) {
        client.close();
        return data[appid.toString()]['data'] as Map<String, dynamic>;
      }
    }
    
    client.close();
    return null;
    
  } catch (e) {
    print("  Error для appid $appid: $e");
    return null;
  }
}

/// Извлекает URL скриншотов из данных игры
List<String> extractScreenshots(Map<String, dynamic> gameData, {int maxScreenshots = 5}) {
  final List<String> screenshots = [];
  
  if (gameData['screenshots'] != null) {
    final List<dynamic> screenshotsData = gameData['screenshots'];
    
    for (var i = 0; i < screenshotsData.length && i < maxScreenshots; i++) {
      final screenshot = screenshotsData[i];
      if (screenshot['path_full'] != null) {
        screenshots.add(screenshot['path_full'] as String);
      } else if (screenshot['path_thumbnail'] != null) {
        screenshots.add(screenshot['path_thumbnail'] as String);
      }
    }
  }
  
  return screenshots;
}

/// Получает разработчика игры
String getDeveloper(Map<String, dynamic> gameData) {
  if (gameData['developers'] != null) {
    final List<dynamic> developers = gameData['developers'];
    if (developers.isNotEmpty) {
      return developers.first as String;
    }
  }
  return '';
}

/// Обновляет данные игр реальными скриншотами
Future<List<Map<String, dynamic>>> updateGameDataWithRealScreenshots(
  List<Map<String, dynamic>> gamesData, 
  {double delay = 1.5}
) async {
  final List<Map<String, dynamic>> updatedGames = [];
  
  print("Обработка ${gamesData.length} игр...\n");
  
  for (var i = 0; i < gamesData.length; i++) {
    final game = gamesData[i];
    print("[${i + 1}/${gamesData.length}] Обработка: ${game['title']}");
    
    final imageUrl = game['imageUrl'] as String;
    
    try {
      // Парсим appid из URL
      final parts = imageUrl.split('/');
      final appsIndex = parts.indexOf('apps');
      
      if (appsIndex == -1 || appsIndex + 1 >= parts.length) {
        print("  Не удалось извлечь appid из URL: $imageUrl");
        updatedGames.add(game);
        continue;
      }
      
      final appid = int.parse(parts[appsIndex + 1]);
      print("  App ID: $appid");
      
      // Получаем данные из Steam API
      final gameDetails = await fetchGameDetails(appid);
      
      if (gameDetails != null) {
        // Обновляем скриншоты
        final realScreenshots = extractScreenshots(gameDetails, maxScreenshots: 5);
        
        if (realScreenshots.isNotEmpty) {
          print("  Найдено скриншотов: ${realScreenshots.length}");
          game['screenshots'] = realScreenshots;
        } else {
          print("  Скриншоты не найдены в API, оставляем текущие");
        }
        
        // Обновляем разработчика если пустой
        final developer = getDeveloper(gameDetails);
        if (developer.isNotEmpty && (game['developer'] == null || game['developer'] == '')) {
          game['developer'] = developer;
          print("  Обновлён разработчик: $developer");
        }
      } else {
        print("  Не удалось получить данные из Steam API");
      }
      
      updatedGames.add(game);
      
      // Задержка между запросами
      if (i < gamesData.length - 1) {
        await Future.delayed(Duration(milliseconds: (delay * 1000).round()));
      }
      
    } catch (e) {
      print("  Ошибка обработки: $e");
      updatedGames.add(game);
    }
  }
  
  return updatedGames;
}

/// Генерирует Dart файл с данными игр
void generateDartFile(List<Map<String, dynamic>> gamesData, String outputPath) {
  final buffer = StringBuffer();
  
  buffer.writeln('// Steam Game Data with real screenshots (auto-generated)');
  buffer.writeln('// Generated by fetch_steam_screenshots.dart');
  buffer.writeln('// Format: https://cdn.cloudflare.steamstatic.com/steam/apps/{appid}/header.jpg');
  buffer.writeln('// Screenshots: fetched from Steam Store API');
  buffer.writeln('');
  buffer.writeln('const List<Map<String, dynamic>> gamesSteamData = [');
  
  for (final game in gamesData) {
    buffer.writeln('  {');
    buffer.writeln('    "id": ${game['id']},');
    buffer.writeln('    "title": "${(game['title'] as String).replaceAll('"', '\\"')}",');
    buffer.writeln('    "genre": "${game['genre']}",');
    buffer.writeln('    "description": "${(game['description'] as String).replaceAll('"', '\\"')}",');
    buffer.writeln('    "releaseDate": "${game['releaseDate']}",');
    buffer.writeln('    "rating": ${game['rating']},');
    buffer.writeln('    "imageUrl": "${game['imageUrl']}",');
    buffer.writeln('    "developer": "${(game['developer'] as String? ?? '').replaceAll('"', '\\"')}",');
    buffer.writeln('    "platforms": ${jsonEncode(game['platforms'])},');
    buffer.writeln('    "status": "${game['status'] ?? 'Released'}",');
    buffer.writeln('    "isFree": ${game['isFree'] ?? false},');
    buffer.writeln('    "trailerUrl": "${game['trailerUrl'] ?? ''}",');
    
    // Скриншоты
    final screenshots = game['screenshots'] as List<dynamic>? ?? [];
    if (screenshots.isNotEmpty) {
      buffer.writeln('    "screenshots": [');
      for (var i = 0; i < screenshots.length; i++) {
        final comma = i < screenshots.length - 1 ? ',' : '';
        buffer.writeln('      "${screenshots[i]}"$comma');
      }
      buffer.writeln('    ]');
    } else {
      buffer.writeln('    "screenshots": []');
    }
    
    buffer.writeln('  },');
  }
  
  buffer.writeln('];');
  
  File(outputPath).writeAsStringSync(buffer.toString());
  print("\nDart файл сохранён: $outputPath");
}

void main() async {
  print("=" * 60);
  print("Steam Screenshots Fetcher (Dart)");
  print("=" * 60);
  
  // Данные игр с их Steam App ID
  final gamesData = [
    {"id": 1, "title": "The Witcher 3: Wild Hunt", "genre": "RPG", 
     "description": "Игра в жанре action/RPG, разработанная польской студией CD Projekt RED.",
     "releaseDate": "2015-05-19", "rating": 9.8, 
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
     "developer": "CD Projekt RED", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
     "status": "Released", "isFree": false, 
     "trailerUrl": "https://www.youtube.com/watch?v=c0i88tKf4SM", "screenshots": []},
    
    {"id": 2, "title": "Cyberpunk 2077", "genre": "RPG",
     "description": "Футуристическая ролевая игра в открытом мире от создателей Ведьмака 3.",
     "releaseDate": "2020-12-10", "rating": 9.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
     "developer": "CD Projekt RED", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=8X2kIfS6fb8", "screenshots": []},
    
    {"id": 3, "title": "Grand Theft Auto V", "genre": "Action",
     "description": "Эпическая приключенческая игра в открытом мире от Rockstar Games.",
     "releaseDate": "2013-09-17", "rating": 9.5,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
     "developer": "Rockstar Games", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=QkkoHAzjnUs", "screenshots": []},
    
    {"id": 4, "title": "Red Dead Redemption 2", "genre": "Adventure",
     "description": "Эпическая сага о Диком Западе от Rockstar Games.",
     "releaseDate": "2018-10-26", "rating": 9.7,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
     "developer": "Rockstar Games", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=eaW0tYpxyp0", "screenshots": []},
    
    {"id": 5, "title": "ELDEN RING", "genre": "RPG",
     "description": "Фэнтезийная action/RPG от FromSoftware и Джорджа Мартина.",
     "releaseDate": "2022-02-25", "rating": 9.6,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
     "developer": "FromSoftware", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=E3Huy2cdih0", "screenshots": []},
    
    {"id": 6, "title": "God of War", "genre": "Action",
     "description": "Продолжение эпического приключения Кратоса и Атрея.",
     "releaseDate": "2022-01-14", "rating": 9.4,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
     "developer": "Santa Monica Studio", "platforms": ["PC", "PlayStation"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=0-3dJv_tq68", "screenshots": []},
    
    {"id": 7, "title": "Horizon Zero Dawn", "genre": "Adventure",
     "description": "Приключения Элой в постапокалиптическом мире.",
     "releaseDate": "2020-08-07", "rating": 9.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg",
     "developer": "Guerrilla Games", "platforms": ["PC", "PlayStation"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=UcJ2liVpKiw", "screenshots": []},
    
    {"id": 8, "title": "Call of Duty: Modern Warfare II", "genre": "Shooter",
     "description": "Современный шутер от первого лица с напряжённым сюжетом.",
     "releaseDate": "2022-10-28", "rating": 8.5,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg",
     "developer": "Infinity Ward", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=OeVapCrN6I8", "screenshots": []},
    
    {"id": 9, "title": "Apex Legends", "genre": "Shooter",
     "description": "Бесплатная королевская битва от Respawn Entertainment.",
     "releaseDate": "2020-11-04", "rating": 9.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg",
     "developer": "Respawn Entertainment", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
     "status": "Released", "isFree": true,
     "trailerUrl": "https://www.youtube.com/watch?v=oQtHENM_GrE", "screenshots": []},
    
    {"id": 10, "title": "Marvel's Spider-Man Remastered", "genre": "Action",
     "description": "Приключения Питера Паркера в Нью-Йорке.",
     "releaseDate": "2022-08-12", "rating": 9.3,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
     "developer": "Insomniac Games", "platforms": ["PC", "PlayStation"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=6ZsVz-r7m_k", "screenshots": []},
    
    {"id": 11, "title": "Resident Evil 4", "genre": "Shooter",
     "description": "Полный ремейк классического хоррора.",
     "releaseDate": "2023-03-24", "rating": 9.4,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
     "developer": "Capcom", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=IdZb2pN1778", "screenshots": []},
    
    {"id": 12, "title": "Street Fighter 6", "genre": "Arcade",
     "description": "Новая глава легендарной fighting-серии.",
     "releaseDate": "2023-06-02", "rating": 9.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1364780/header.jpg",
     "developer": "Capcom", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=3b4g1y61AM8", "screenshots": []},
    
    {"id": 13, "title": "Hogwarts Legacy", "genre": "Adventure",
     "description": "Ролевая игра во вселенной Гарри Поттера.",
     "releaseDate": "2023-02-10", "rating": 8.8,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg",
     "developer": "Avalanche Software", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=1O6Q81nJz2o", "screenshots": []},
    
    {"id": 14, "title": "Dead Space", "genre": "Shooter",
     "description": "Полный ремейк культового sci-fi хоррора.",
     "releaseDate": "2023-01-27", "rating": 9.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg",
     "developer": "Motive Studio", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=colJ3D9V6cE", "screenshots": []},
    
    {"id": 15, "title": "Baldur's Gate 3", "genre": "RPG",
     "description": "Эпическая ролевая игра по мотивам Dungeons & Dragons.",
     "releaseDate": "2023-08-03", "rating": 9.8,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
     "developer": "Larian Studios", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=OiC5rxANBjk", "screenshots": []},
    
    {"id": 16, "title": "Starfield", "genre": "RPG",
     "description": "Эпическая научно-фантастическая RPG от Bethesda.",
     "releaseDate": "2023-09-06", "rating": 8.0,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg",
     "developer": "Bethesda Game Studios", "platforms": ["PC", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=zmb2FJKvn8U", "screenshots": []},
    
    {"id": 17, "title": "It Takes Two", "genre": "Adventure",
     "description": "Кооперативное приключение для двух игроков.",
     "releaseDate": "2021-03-26", "rating": 9.5,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg",
     "developer": "Hazelight Studios", "platforms": ["PC", "PlayStation", "Xbox"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=ohClxMm-uR0", "screenshots": []},
    
    {"id": 18, "title": "Hades", "genre": "Action",
     "description": "Культовый рогалик от Supergiant Games.",
     "releaseDate": "2020-09-17", "rating": 9.5,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg",
     "developer": "Supergiant Games", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=91t0BX9w6wE", "screenshots": []},
    
    {"id": 19, "title": "Stardew Valley", "genre": "Simulation",
     "description": "Уютная фермерская симуляция с элементами RPG.",
     "releaseDate": "2016-02-26", "rating": 9.3,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg",
     "developer": "ConcernedApe", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch", "Mobile"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=ot7uXNQYbYc", "screenshots": []},
    
    {"id": 20, "title": "Hollow Knight", "genre": "Adventure",
     "description": "Метроидвания с уникальным арт-стилем.",
     "releaseDate": "2017-02-24", "rating": 9.4,
     "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
     "developer": "Team Cherry", "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
     "status": "Released", "isFree": false,
     "trailerUrl": "https://www.youtube.com/watch?v=UAO2urG23S4", "screenshots": []},
  ];
  
  // Обновляем данные реальными скриншотами
  final updatedGames = await updateGameDataWithRealScreenshots(gamesData);
  
  // Генерируем Dart файл
  const outputPath = "lib/data/games_data_steam_updated.dart";
  generateDartFile(updatedGames, outputPath);
  
  print("\n" + "=" * 60);
  print("Готово!");
  print("Обновлённый файл: $outputPath");
  print("\nИнструкция:");
  print("1. Проверьте сгенерированный файл");
  print("2. Замените games_data_steam.dart на новый файл");
  print("3. Или скопируйте содержимое в существующий файл");
  print("=" * 60);
}
