// Steam Game Data with real screenshots (auto-generated)
// Generated by fetch_steam_screenshots.dart
// Format: https://cdn.cloudflare.steamstatic.com/steam/apps/{appid}/header.jpg
// Screenshots: fetched from Steam Store API

const List<Map<String, dynamic>> gamesSteamData = [
  {
    "id": 1,
    "title": "The Witcher 3: Wild Hunt",
    "genre": "RPG",
    "description": "Игра в жанре action/RPG, разработанная польской студией CD Projekt RED.",
    "releaseDate": "2015-05-19",
    "rating": 9.8,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
    "developer": "CD Projekt RED",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=c0i88tKf4SM",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_5710298af2318afd9aa72449ef29ac4a2ef64d8e.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_0901e64e9d4b8ebaea8348c194e7a3644d2d832d.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_112b1e176c1bd271d8a565eacb6feaf90f240bb2.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_d1b73b18cbcd5e9e412c7a1dead3c5cd7303d2ad.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_107600c1337accc09104f7a8aa7f275f23cad096.1920x1080.jpg?t=1768303991"
    ]
  },
  {
    "id": 2,
    "title": "Cyberpunk 2077",
    "genre": "RPG",
    "description": "Футуристическая ролевая игра в открытом мире от создателей Ведьмака 3.",
    "releaseDate": "2020-12-10",
    "rating": 9.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    "developer": "CD Projekt RED",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=8X2kIfS6fb8",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_2f649b68d579bf87011487d29bc4ccbfdd97d34f.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_0e64170751e1ae20ff8fdb7001a8892fd48260e7.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_af2804aa4bf35d4251043744412ce3b359a125ef.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_7924f64b6e5d586a80418c9896a1c92881a7905b.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_4eb068b1cf52c91b57157b84bed18a186ed7714b.1920x1080.jpg?t=1769690377"
    ]
  },
  {
    "id": 3,
    "title": "Grand Theft Auto V",
    "genre": "Action",
    "description": "Эпическая приключенческая игра в открытом мире от Rockstar Games.",
    "releaseDate": "2013-09-17",
    "rating": 9.5,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
    "developer": "Rockstar Games",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=QkkoHAzjnUs",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_32aa18ab3175e3002217862dd5917646d298ab6b.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_2744f112fa060320d191a50e8b3a92441a648a56.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_da39c16db175f6973770bae6b91d411251763152.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_bd5db78286be0a7c6b2c62519099a9e27e6b06f3.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_b1a1cb7959d6a0e6fcb2d06ebf97a66c9055cef3.1920x1080.jpg?t=1765387725"
    ]
  },
  {
    "id": 4,
    "title": "Red Dead Redemption 2",
    "genre": "Adventure",
    "description": "Эпическая сага о Диком Западе от Rockstar Games.",
    "releaseDate": "2018-10-26",
    "rating": 9.7,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
    "developer": "Rockstar Games",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=eaW0tYpxyp0",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_66b553f4c209476d3e4ce25fa4714002cc914c4f.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_bac60bacbf5da8945103648c08d27d5e202444ca.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_668dafe477743f8b50b818d5bbfcec669e9ba93e.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_4ce07ae360b166f0f650e9a895a3b4b7bf15e34f.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_d1a8f5a69155c3186c65d1da90491fcfd43663d9.1920x1080.jpg?t=1759502961"
    ]
  },
  {
    "id": 5,
    "title": "ELDEN RING",
    "genre": "RPG",
    "description": "Фэнтезийная action/RPG от FromSoftware и Джорджа Мартина.",
    "releaseDate": "2022-02-25",
    "rating": 9.6,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    "developer": "FromSoftware",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=E3Huy2cdih0",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_943bf6fe62352757d9070c1d33e50b92fe8539f1.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_dcdac9e4b26ac0ee5248bfd2967d764fd00cdb42.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_3c41384a24d86dddd58a8f61db77f9dc0bfda8b5.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_e0316c76f8197405c1312d072b84331dd735d60b.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_ef61b771ee6b269b1f0cb484233e07a0bfb5f81b.1920x1080.jpg?t=1767883716"
    ]
  },
  {
    "id": 6,
    "title": "God of War",
    "genre": "Action",
    "description": "Продолжение эпического приключения Кратоса и Атрея.",
    "releaseDate": "2022-01-14",
    "rating": 9.4,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
    "developer": "Santa Monica Studio",
    "platforms": ["PC","PlayStation"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=0-3dJv_tq68",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_6eccc970b5de2943546d93d319be1b5c0618f21b.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_f1bff24d3967a21d303d95e11ed892e3d9113057.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_3670ba72c7e3e9c3c3225547ef2c1053504e62b8.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_93a3ca63aa2cd8c675bbb6430324ee3f2d44b845.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_1bd99270dcbd4ff9fe9c94b0d9c8ffc50ebb42c7.1920x1080.jpg?t=1763059412"
    ]
  },
  {
    "id": 7,
    "title": "Horizon Zero Dawn",
    "genre": "Adventure",
    "description": "Приключения Элой в постапокалиптическом мире.",
    "releaseDate": "2020-08-07",
    "rating": 9.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg",
    "developer": "Guerrilla Games",
    "platforms": ["PC","PlayStation"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=UcJ2liVpKiw",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_d09106060fb7de8bf342c23df18b14debc8a15a3.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_271f850eec3f96b22aa17be35b948268e0771c7f.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_15f5759c441e4e5f51e1a8ee333e4ab9df9aa783.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_f7cf51f1ccd909264f2c5814f328e3f72e7b62bd.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_9db45aa04e8c8b5043b479f42ed36296bfc3a918.1920x1080.jpg?t=1776465788"
    ]
  },
  {
    "id": 8,
    "title": "Call of Duty: Modern Warfare II",
    "genre": "Shooter",
    "description": "Современный шутер от первого лица с напряжённым сюжетом.",
    "releaseDate": "2022-10-28",
    "rating": 8.5,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg",
    "developer": "Infinity Ward",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=OeVapCrN6I8",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/10be1d8a9b68f19a7b0321f4adc819374955268d/ss_10be1d8a9b68f19a7b0321f4adc819374955268d.1920x1080.jpg?t=1775145994",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/6781fd040d6b20a45602b316cabc65720ae63d1f/ss_6781fd040d6b20a45602b316cabc65720ae63d1f.1920x1080.jpg?t=1775145994",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/e70521017a69590d0ae490558e7c0c316d153701/ss_e70521017a69590d0ae490558e7c0c316d153701.1920x1080.jpg?t=1775145994",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/ac2402cb806a974535c32f2f9969f1790d47d039/ss_ac2402cb806a974535c32f2f9969f1790d47d039.1920x1080.jpg?t=1775145994",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/c805f95815551c4d9228be054e1a7982210e4698/ss_c805f95815551c4d9228be054e1a7982210e4698.1920x1080.jpg?t=1775145994"
    ]
  },
  {
    "id": 9,
    "title": "Apex Legends",
    "genre": "Shooter",
    "description": "Бесплатная королевская битва от Respawn Entertainment.",
    "releaseDate": "2020-11-04",
    "rating": 9.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg",
    "developer": "Respawn Entertainment",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch"],
    "status": "Released",
    "isFree": true,
    "trailerUrl": "https://www.youtube.com/watch?v=oQtHENM_GrE",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/d86d5fe798addd4ff7219938f891268affb1ea2d/ss_d86d5fe798addd4ff7219938f891268affb1ea2d.1920x1080.jpg?t=1770753360",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/f786d0d1e567be0e5a801a62855970f9b6bae6fd/ss_f786d0d1e567be0e5a801a62855970f9b6bae6fd.1920x1080.jpg?t=1770753360",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/c1f5eb613c365fc96f5d59dd69bd852793929f69/ss_c1f5eb613c365fc96f5d59dd69bd852793929f69.1920x1080.jpg?t=1770753360",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/3424111e83c2adfc7e6c056573d5089c27fdc711/ss_3424111e83c2adfc7e6c056573d5089c27fdc711.1920x1080.jpg?t=1770753360",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/339c1a98c4ae3a6d662e2766cad9660c3ca8f8aa/ss_339c1a98c4ae3a6d662e2766cad9660c3ca8f8aa.1920x1080.jpg?t=1770753360"
    ]
  },
  {
    "id": 10,
    "title": "Marvel's Spider-Man Remastered",
    "genre": "Action",
    "description": "Приключения Питера Паркера в Нью-Йорке.",
    "releaseDate": "2022-08-12",
    "rating": 9.3,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
    "developer": "Insomniac Games",
    "platforms": ["PC","PlayStation"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=6ZsVz-r7m_k",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_dfe778bf6d66e952e4acd4e1f926f7615b609ddf.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_427677cf78195df94702f0a963cd9eaeb9d8935a.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_dfba6f2477bfa42be69ddfdffbd421d3943d20bf.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_5b5448df07bc74ba236f2c007fd0ec19cc1d22b6.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_ad14a7daa190cb150fbb070afc70bc64d66a5e2e.1920x1080.jpg?t=1763569047"
    ]
  },
  {
    "id": 11,
    "title": "Resident Evil 4",
    "genre": "Shooter",
    "description": "Полный ремейк классического хоррора.",
    "releaseDate": "2023-03-24",
    "rating": 9.4,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
    "developer": "Capcom",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=IdZb2pN1778",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_59d1b19964cc532213df92c8287b75a0bffeb33c.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_ab807f8ad9e968a620777caf483cb6020367b9ee.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_0442f7fb4327d79802c2db8ea8d23d228a28d896.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_69810f4cd155912fdfdd21da70181df7d454c874.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_0596bac955340495562f3ff2538756ebd9a7f073.1920x1080.jpg?t=1772502922"
    ]
  },
  {
    "id": 12,
    "title": "Street Fighter 6",
    "genre": "Arcade",
    "description": "Новая глава легендарной fighting-серии.",
    "releaseDate": "2023-06-02",
    "rating": 9.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1364780/header.jpg",
    "developer": "Capcom",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=3b4g1y61AM8",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_387137f8cccb048c35a8685634372e97785d40aa.1920x1080.jpg?t=1773812087",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_a381f1b3b450c18900d47b991ce8e7456e9cdba5.1920x1080.jpg?t=1773812087",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_f62ce93269a6d8e0027853358af4d6368e2c4b93.1920x1080.jpg?t=1773812087",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_d186566a92ada8cdb08b04769a8c95cd1e380006.1920x1080.jpg?t=1773812087",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_ed46aaa9ed94dd6f35a703070f8df16cee5aef61.1920x1080.jpg?t=1773812087"
    ]
  },
  {
    "id": 13,
    "title": "Hogwarts Legacy",
    "genre": "Adventure",
    "description": "Ролевая игра во вселенной Гарри Поттера.",
    "releaseDate": "2023-02-10",
    "rating": 8.8,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg",
    "developer": "Avalanche Software",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=1O6Q81nJz2o",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_725bf58485beb4aa37a3a69c1e2baa69bf3e4653.1920x1080.jpg?t=1773932856",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_df93b5e8a183f7232d68be94ae78920a90de1443.1920x1080.jpg?t=1773932856",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_94058497bf0f8fabdde17ee8d59bece609a60663.1920x1080.jpg?t=1773932856",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_8e08976236d29b1897769257ac3c64e9264792a5.1920x1080.jpg?t=1773932856",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_d4930d675af053dc1e61a876a34fc003e85e261f.1920x1080.jpg?t=1773932856"
    ]
  },
  {
    "id": 14,
    "title": "Dead Space",
    "genre": "Shooter",
    "description": "Полный ремейк культового sci-fi хоррора.",
    "releaseDate": "2023-01-27",
    "rating": 9.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1693980/header.jpg",
    "developer": "Motive Studio",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=colJ3D9V6cE",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_b4b02766216117747640523bb6e258d44053e355.1920x1080.jpg?t=1769464545",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_179cb4f80343d464ea2d7712b5982555271ad707.1920x1080.jpg?t=1769464545",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_06f8cc8ad27e53078b09df03c5c3fb1c75459960.1920x1080.jpg?t=1769464545",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_a7a0bceba764978d54ff0bb7ba0f0aa08487cd05.1920x1080.jpg?t=1769464545",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_973768134ba80cf0d591a4f0a834b8ae10ddca93.1920x1080.jpg?t=1769464545"
    ]
  },
  {
    "id": 15,
    "title": "Baldur's Gate 3",
    "genre": "RPG",
    "description": "Эпическая ролевая игра по мотивам Dungeons & Dragons.",
    "releaseDate": "2023-08-03",
    "rating": 9.8,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    "developer": "Larian Studios",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=OiC5rxANBjk",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_c73bc54415178c07fef85f54ee26621728c77504.1920x1080.jpg?t=1773079016",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_73d93bea842b93914d966622104dcb8c0f42972b.1920x1080.jpg?t=1773079016",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_cf936d31061b58e98e0c646aee00e6030c410cda.1920x1080.jpg?t=1773079016",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_b6a6ee6e046426d08ceea7a4506a1b5f44181543.1920x1080.jpg?t=1773079016",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_6b8faba0f6831a406ce015648958da9612d14dbb.1920x1080.jpg?t=1773079016"
    ]
  },
  {
    "id": 16,
    "title": "Starfield",
    "genre": "RPG",
    "description": "Эпическая научно-фантастическая RPG от Bethesda.",
    "releaseDate": "2023-09-06",
    "rating": 8.0,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg",
    "developer": "Bethesda Game Studios",
    "platforms": ["PC","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=zmb2FJKvn8U",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_4887dc140a637684ddcfca518458668409f946dc.1920x1080.jpg?t=1775743548",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_b2821283cb140cd5a6289a8160016b6a60d8f96e.1920x1080.jpg?t=1775743548",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_68f15d580bf91971f637be5e464bc803482d78f7.1920x1080.jpg?t=1775743548",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_aae99c177004bb5ec653d2fcb65a5d30489ec7b8.1920x1080.jpg?t=1775743548",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_c8594798fadfd8e042b2fc8afff7bcf4872c5198.1920x1080.jpg?t=1775743548"
    ]
  },
  {
    "id": 17,
    "title": "It Takes Two",
    "genre": "Adventure",
    "description": "Кооперативное приключение для двух игроков.",
    "releaseDate": "2021-03-26",
    "rating": 9.5,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg",
    "developer": "Hazelight Studios",
    "platforms": ["PC","PlayStation","Xbox"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=ohClxMm-uR0",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_3e59753eefaba9a7704a18e902b48e8d38e95e0b.1920x1080.jpg?t=1763484491",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_6e987a0678b013bfd0073a9ac4703e1f04ca4dea.1920x1080.jpg?t=1763484491",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_fdac523e3ea4d2f32a44449bb8c224857563bd7d.1920x1080.jpg?t=1763484491",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_4a62bc8fa398fc5b2094a6225dc5ecff9485f824.1920x1080.jpg?t=1763484491",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_a15164ddd357ab3c0b2aff575a6b215b2d91b406.1920x1080.jpg?t=1763484491"
    ]
  },
  {
    "id": 18,
    "title": "Hades",
    "genre": "Action",
    "description": "Культовый рогалик от Supergiant Games.",
    "releaseDate": "2020-09-17",
    "rating": 9.5,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg",
    "developer": "Supergiant Games",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=91t0BX9w6wE",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_c0fed447426b69981cf1721756acf75369801b31.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_8a9f0953e8a014bd3df2789c2835cb787cd3764d.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_68300459a8c3daacb2ec687adcdbf4442fcc4f47.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_bcb499a0dd001f4101823f99ec5094d2872ba6ee.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_8e07e477fa7ff2f88c8984bc89b9652a655da0e9.1920x1080.jpg?t=1758127023"
    ]
  },
  {
    "id": 19,
    "title": "Stardew Valley",
    "genre": "Simulation",
    "description": "Уютная фермерская симуляция с элементами RPG.",
    "releaseDate": "2016-02-26",
    "rating": 9.3,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg",
    "developer": "ConcernedApe",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch","Mobile"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=ot7uXNQYbYc",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_b887651a93b0525739049eb4194f633de2df75be.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_9ac899fe2cda15d48b0549bba77ef8c4a090a71c.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_4fa0866709ede3753fdf2745349b528d5e8c4054.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_d836f0a5b0447fb6a2bdb0a6ac5f954949d3c41e.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_10628b4a811c0a925a1433d4323f78c7017dbbe4.1920x1080.jpg?t=1754692865"
    ]
  },
  {
    "id": 20,
    "title": "Hollow Knight",
    "genre": "Adventure",
    "description": "Метроидвания с уникальным арт-стилем.",
    "releaseDate": "2017-02-24",
    "rating": 9.4,
    "imageUrl": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
    "developer": "Team Cherry",
    "platforms": ["PC","PlayStation","Xbox","Nintendo Switch"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "https://www.youtube.com/watch?v=UAO2urG23S4",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_5384f9f8b96a0b9934b2bc35a4058376211636d2.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_d5b6edd94e77ba6db31c44d8a3c09d807ab27751.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_a81e4231cc8d55f58b51a4a938898af46503cae5.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_62e10cf506d461e11e050457b08aa0e2a1c078d0.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_bd76bd88bc5334ee56ae3d5f0d8dec4455e8e3b8.1920x1080.jpg?t=1776125684"
    ]
  },
];
