// Steam Game Data with real screenshots from Steam API
// Auto-generated by fetch_steam_data.py

const List<Map<String, dynamic>> gamesSteamData = [
  {
    "id": 292030,
    "title": "The Witcher 3: Wild Hunt",
    "genre": "RPG",
    "description": "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world.",
    "releaseDate": "2015-05-18",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ad9240e088f953a84aee814034c50a6a92bf4516/header.jpg?t=1768303991",
    "developer": "CD PROJEKT RED",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_5710298af2318afd9aa72449ef29ac4a2ef64d8e.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_0901e64e9d4b8ebaea8348c194e7a3644d2d832d.1920x1080.jpg?t=1768303991",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/ss_112b1e176c1bd271d8a565eacb6feaf90f240bb2.1920x1080.jpg?t=1768303991"
    ]
  },
  {
    "id": 1091500,
    "title": "Cyberpunk 2077",
    "genre": "RPG",
    "description": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
    "releaseDate": "2020-12-09",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/e9047d8ec47ae3d94bb8b464fb0fc9e9972b4ac7/header.jpg?t=1769690377",
    "developer": "CD PROJEKT RED",
    "platforms": ["PC", "Mac"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_2f649b68d579bf87011487d29bc4ccbfdd97d34f.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_0e64170751e1ae20ff8fdb7001a8892fd48260e7.1920x1080.jpg?t=1769690377",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/ss_af2804aa4bf35d4251043744412ce3b359a125ef.1920x1080.jpg?t=1769690377"
    ]
  },
  {
    "id": 271590,
    "title": "Grand Theft Auto V Legacy",
    "genre": "Action",
    "description": "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.",
    "releaseDate": "2015-04-13",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg?t=1765387725",
    "developer": "Rockstar North",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_32aa18ab3175e3002217862dd5917646d298ab6b.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_2744f112fa060320d191a50e8b3a92441a648a56.1920x1080.jpg?t=1765387725",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/ss_da39c16db175f6973770bae6b91d411251763152.1920x1080.jpg?t=1765387725"
    ]
  },
  {
    "id": 1174180,
    "title": "Red Dead Redemption 2",
    "genre": "Action",
    "description": "Arthur Morgan and the Van der Linde Gang are outlaws on the run. With federal agents and bounty hunters massing on their heels, the gang must rob, steal, and fight their way across the rugged heartland in order to survive.",
    "releaseDate": "2019-12-05",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg?t=1759502961",
    "developer": "Rockstar Games",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_66b553f4c209476d3e4ce25fa4714002cc914c4f.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_bac60bacbf5da8945103648c08d27d5e202444ca.1920x1080.jpg?t=1759502961",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/ss_668dafe477743f8b50b818d5bbfcec669e9ba93e.1920x1080.jpg?t=1759502961"
    ]
  },
  {
    "id": 1245620,
    "title": "ELDEN RING",
    "genre": "Action",
    "description": "THE CRITICALLY ACCLAIMED FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    "releaseDate": "2022-02-24",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg?t=1767883716",
    "developer": "FromSoftware, Inc.",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_943bf6fe62352757d9070c1d33e50b92fe8539f1.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_dcdac9e4b26ac0ee5248bfd2967d764fd00cdb42.1920x1080.jpg?t=1767883716",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_3c41384a24d86dddd58a8f61db77f9dc0bfda8b5.1920x1080.jpg?t=1767883716"
    ]
  },
  {
    "id": 1593500,
    "title": "God of War",
    "genre": "Action",
    "description": "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same.",
    "releaseDate": "2022-01-14",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg?t=1763059412",
    "developer": "Santa Monica Studio",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_6eccc970b5de2943546d93d319be1b5c0618f21b.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_f1bff24d3967a21d303d95e11ed892e3d9113057.1920x1080.jpg?t=1763059412",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/ss_3670ba72c7e3e9c3c3225547ef2c1053504e62b8.1920x1080.jpg?t=1763059412"
    ]
  },
  {
    "id": 1151640,
    "title": "Horizon Zero Dawn™ Complete Edition",
    "genre": "Action",
    "description": "Experience Aloy’s legendary quest to unravel the mysteries of a future Earth ruled by Machines. Use devastating tactical attacks against your prey and explore a majestic open world in this award-winning action RPG!",
    "releaseDate": "2020-08-07",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/header.jpg?t=1776465788",
    "developer": "Guerrilla",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_d09106060fb7de8bf342c23df18b14debc8a15a3.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_271f850eec3f96b22aa17be35b948268e0771c7f.1920x1080.jpg?t=1776465788",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1151640/ss_15f5759c441e4e5f51e1a8ee333e4ab9df9aa783.1920x1080.jpg?t=1776465788"
    ]
  },
  {
    "id": 990080,
    "title": "Hogwarts Legacy",
    "genre": "Action",
    "description": "Hogwarts Legacy is an immersive, open-world action RPG. Now you can take control of the action and be at the center of your own adventure in the wizarding world.",
    "releaseDate": "2023-02-10",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/a3cdc6f40d97df8ac993679c2dd1edeb5222421e/header.jpg?t=1778797474",
    "developer": "Avalanche Software",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_725bf58485beb4aa37a3a69c1e2baa69bf3e4653.1920x1080.jpg?t=1778797474",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_df93b5e8a183f7232d68be94ae78920a90de1443.1920x1080.jpg?t=1778797474",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/ss_94058497bf0f8fabdde17ee8d59bece609a60663.1920x1080.jpg?t=1778797474"
    ]
  },
  {
    "id": 1086940,
    "title": "Baldur's Gate 3",
    "genre": "Adventure",
    "description": "Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons &amp; Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.",
    "releaseDate": "2023-08-03",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/48a2fcbda8565bb45025e98fd8ebde8a7203f6a0/header.jpg?t=1777363040",
    "developer": "Larian Studios",
    "platforms": ["PC", "Mac"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_c73bc54415178c07fef85f54ee26621728c77504.1920x1080.jpg?t=1777363040",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_73d93bea842b93914d966622104dcb8c0f42972b.1920x1080.jpg?t=1777363040",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/ss_cf936d31061b58e98e0c646aee00e6030c410cda.1920x1080.jpg?t=1777363040"
    ]
  },
  {
    "id": 1817070,
    "title": "Marvel’s Spider-Man Remastered",
    "genre": "Action",
    "description": "In Marvel’s Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide in an original action-packed story. Play as an experienced Peter Parker, fighting big crime and iconic villains in Marvel’s New York. Web-swing through vibrant neighborhoods and defeat villains with epic takedowns.",
    "releaseDate": "2022-08-12",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/header.jpg?t=1763569047",
    "developer": "Insomniac Games",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_dfe778bf6d66e952e4acd4e1f926f7615b609ddf.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_427677cf78195df94702f0a963cd9eaeb9d8935a.1920x1080.jpg?t=1763569047",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/ss_dfba6f2477bfa42be69ddfdffbd421d3943d20bf.1920x1080.jpg?t=1763569047"
    ]
  },
  {
    "id": 2050650,
    "title": "Resident Evil 4",
    "genre": "Action",
    "description": "Survival is just the beginning. Six years have passed since the biological disaster in Raccoon City. Leon S. Kennedy, one of the survivors, tracks the president's kidnapped daughter to a secluded European village, where there is something terribly wrong with the locals.",
    "releaseDate": "2023-03-23",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg?t=1772502922",
    "developer": "CAPCOM Co., Ltd.",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_59d1b19964cc532213df92c8287b75a0bffeb33c.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_ab807f8ad9e968a620777caf483cb6020367b9ee.1920x1080.jpg?t=1772502922",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/ss_0442f7fb4327d79802c2db8ea8d23d228a28d896.1920x1080.jpg?t=1772502922"
    ]
  },
  {
    "id": 1364780,
    "title": "Street Fighter™ 6",
    "genre": "Action",
    "description": "Here comes Capcom’s newest challenger! Street Fighter™ 6 launches worldwide on June 2nd, 2023 and represents the next evolution of the Street Fighter™ series! Street Fighter 6 spans three distinct game modes, including World Tour, Fighting Ground and Battle Hub.",
    "releaseDate": "2023-06-01",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/header.jpg?t=1780982579",
    "developer": "CAPCOM Co., Ltd.",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_387137f8cccb048c35a8685634372e97785d40aa.1920x1080.jpg?t=1780982579",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_a381f1b3b450c18900d47b991ce8e7456e9cdba5.1920x1080.jpg?t=1780982579",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1364780/ss_f62ce93269a6d8e0027853358af4d6368e2c4b93.1920x1080.jpg?t=1780982579"
    ]
  },
  {
    "id": 1938090,
    "title": "Call of Duty®",
    "genre": "Action",
    "description": "The Call of Duty® experience supports Modern Warfare® 4, Black Ops 7, Black Ops 6 and Call of Duty®: Warzone™.",
    "releaseDate": "2022-10-27",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/23af6cf41e2d09620caa07700a4cb3288dbcbaa8/header.jpg?t=1781029517",
    "developer": "Treyarch",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/ee5f6b6aebe4dc9e86b49c4e309d361b132df308/ss_ee5f6b6aebe4dc9e86b49c4e309d361b132df308.1920x1080.jpg?t=1781029517",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/ca97243a998802a38c7cddf195cee327c5760353/ss_ca97243a998802a38c7cddf195cee327c5760353.1920x1080.jpg?t=1781029517",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1938090/6b8f4040a1e923f036e04d9eb21ecb0f866be57e/ss_6b8f4040a1e923f036e04d9eb21ecb0f866be57e.1920x1080.jpg?t=1781029517"
    ]
  },
  {
    "id": 1693980,
    "title": "Dead Space",
    "genre": "Action",
    "description": "The sci-fi survival-horror classic returns, completely rebuilt to offer an even more immersive experience — including visual, audio, and gameplay improvements — while staying faithful to the original game’s thrilling vision.",
    "releaseDate": "2023-01-27",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/header.jpg?t=1777396576",
    "developer": "Motive",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_b4b02766216117747640523bb6e258d44053e355.1920x1080.jpg?t=1777396576",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_179cb4f80343d464ea2d7712b5982555271ad707.1920x1080.jpg?t=1777396576",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1693980/ss_06f8cc8ad27e53078b09df03c5c3fb1c75459960.1920x1080.jpg?t=1777396576"
    ]
  },
  {
    "id": 1716740,
    "title": "Starfield",
    "genre": "RPG",
    "description": "Starfield is the first new universe in 25 years from Bethesda Game Studios, the award-winning creators of The Elder Scrolls V: Skyrim and Fallout 4.",
    "releaseDate": "2023-09-05",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg?t=1778168061",
    "developer": "Bethesda Game Studios",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_4887dc140a637684ddcfca518458668409f946dc.1920x1080.jpg?t=1778168061",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_b2821283cb140cd5a6289a8160016b6a60d8f96e.1920x1080.jpg?t=1778168061",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1716740/ss_68f15d580bf91971f637be5e464bc803482d78f7.1920x1080.jpg?t=1778168061"
    ]
  },
  {
    "id": 1426210,
    "title": "It Takes Two",
    "genre": "Action",
    "description": "Embark on the craziest journey of your life in It Takes Two. Invite a friend to join for free with Friend’s Pass and work together across a huge variety of gleefully disruptive gameplay challenges. Winner of GAME OF THE YEAR at the Game Awards 2021.",
    "releaseDate": "2021-03-25",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/header.jpg?t=1777395376",
    "developer": "Hazelight Studios",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_3e59753eefaba9a7704a18e902b48e8d38e95e0b.1920x1080.jpg?t=1777395376",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_6e987a0678b013bfd0073a9ac4703e1f04ca4dea.1920x1080.jpg?t=1777395376",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1426210/ss_fdac523e3ea4d2f32a44449bb8c224857563bd7d.1920x1080.jpg?t=1777395376"
    ]
  },
  {
    "id": 1145360,
    "title": "Hades",
    "genre": "Action",
    "description": "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    "releaseDate": "2020-09-17",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg?t=1758127023",
    "developer": "Supergiant Games",
    "platforms": ["PC", "Mac"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_c0fed447426b69981cf1721756acf75369801b31.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_8a9f0953e8a014bd3df2789c2835cb787cd3764d.1920x1080.jpg?t=1758127023",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/ss_68300459a8c3daacb2ec687adcdbf4442fcc4f47.1920x1080.jpg?t=1758127023"
    ]
  },
  {
    "id": 413150,
    "title": "Stardew Valley",
    "genre": "Indie",
    "description": "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?",
    "releaseDate": "2016-02-26",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg?t=1754692865",
    "developer": "ConcernedApe",
    "platforms": ["PC", "Mac", "Linux"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_b887651a93b0525739049eb4194f633de2df75be.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_9ac899fe2cda15d48b0549bba77ef8c4a090a71c.1920x1080.jpg?t=1754692865",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/ss_4fa0866709ede3753fdf2745349b528d5e8c4054.1920x1080.jpg?t=1754692865"
    ]
  },
  {
    "id": 367520,
    "title": "Hollow Knight",
    "genre": "Action",
    "description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.",
    "releaseDate": "2017-02-24",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/3c3489495136b26b34f8a9543c7f5645b99d388c/header.jpg?t=1776125684",
    "developer": "Team Cherry",
    "platforms": ["PC", "Mac", "Linux"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_5384f9f8b96a0b9934b2bc35a4058376211636d2.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_d5b6edd94e77ba6db31c44d8a3c09d807ab27751.1920x1080.jpg?t=1776125684",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/ss_a81e4231cc8d55f58b51a4a938898af46503cae5.1920x1080.jpg?t=1776125684"
    ]
  },
  {
    "id": 1172470,
    "title": "Apex Legends™",
    "genre": "Action",
    "description": "Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.",
    "releaseDate": "2020-11-04",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/0bd74245b869287a2dc7f682e6013f7ed08d98e3/header.jpg?t=1778502442",
    "developer": "Respawn",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/0ae2c002aa75d0b7309955960181fe402327d330/ss_0ae2c002aa75d0b7309955960181fe402327d330.1920x1080.jpg?t=1778502442",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/c07b405c6272c5dc2f6f25b76591c93ed8711c1d/ss_c07b405c6272c5dc2f6f25b76591c93ed8711c1d.1920x1080.jpg?t=1778502442",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/96cb3e1aaf5b7f3f0130a4924e5357cca565e1b3/ss_96cb3e1aaf5b7f3f0130a4924e5357cca565e1b3.1920x1080.jpg?t=1778502442"
    ]
  },
  {
    "id": 1885730,
    "title": "The Brothers",
    "genre": "Adventure",
    "description": "The Brothers is a classically styled 2D JRPG featuring Octopath Traveller inspired combat, with modern features you can't live without: Auto saving, quest logs, a built in encyclopaedia and a digital manual just scratch the surface.",
    "releaseDate": "2024-01-01",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1885730/header.jpg?t=1763669201",
    "developer": "System Masters",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1885730/ss_60c4dd8ba727d31b8c6453b06dec51abe97d2a95.1920x1080.jpg?t=1763669201",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1885730/ss_123f5b5bc1832cd3de5c7919694650db7bfe7b57.1920x1080.jpg?t=1763669201",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1885730/ss_405a491ab9c6aa693ae058bdcbd4e4823dca2244.1920x1080.jpg?t=1763669201"
    ]
  },
  {
    "id": 1659040,
    "title": "HITMAN World of Assassination",
    "genre": "Action",
    "description": "Enter the world of the ultimate assassin. HITMAN World of Assassination delivers the definitive stealth action experience, putting you in the shoes of Agent 47, a master assassin. Explore immersive locations, uncover hidden secrets, and eliminate targets with complete freedom of approach.",
    "releaseDate": "2022-01-20",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/c62446d5c95f583a296d7f1b99045a61e2f81dea/header.jpg?t=1780915221",
    "developer": "IO Interactive A/S",
    "platforms": ["PC", "Mac"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/035da4d379ca1bdd0ac67e9f154a8d008ba695a6/ss_035da4d379ca1bdd0ac67e9f154a8d008ba695a6.1920x1080.jpg?t=1780915221",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/2a25834600637e626d6f6e3ea7604badde7206db/ss_2a25834600637e626d6f6e3ea7604badde7206db.1920x1080.jpg?t=1780915221",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/ss_f3a815f62dea7af43eebff863b49ded1bcf8098e.1920x1080.jpg?t=1780915221"
    ]
  },
  {
    "id": 1971650,
    "title": "OCTOPATH TRAVELER II",
    "genre": "RPG",
    "description": "This game is a brand-new entry in the OCTOPATH TRAVELER series, the first installment of which was initially released in 2018 and sold over 3 million copies worldwide.",
    "releaseDate": "2023-02-24",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971650/header.jpg?t=1775032200",
    "developer": "Square Enix",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971650/ss_063d6228ccd9256814aec0cd46ebb4c093b56fea.1920x1080.jpg?t=1775032200",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971650/ss_dd347306294990fbb93e88a9fb6d694a7a2eec13.1920x1080.jpg?t=1775032200",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1971650/ss_ffcc9f56fdf7d36ad4c0414dd2d85ed7389b42fe.1920x1080.jpg?t=1775032200"
    ]
  },
  {
    "id": 1962660,
    "title": "Call of Duty®: Modern Warfare® II",
    "genre": "Action",
    "description": "Call of Duty®: Modern Warfare® II drops players into an unprecedented global conflict that features the iconic Operators of Task Force 141.",
    "releaseDate": "2022-10-22",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3595230/ce4d5e53b36cb9d3c4309d1df72bf8663bbbc7ef/header.jpg?t=1778886532",
    "developer": "Infinity Ward",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3595230/1c3624c55a8b7d6f49f9ffe7f8e4a2ac71aab0c6/ss_1c3624c55a8b7d6f49f9ffe7f8e4a2ac71aab0c6.1920x1080.jpg?t=1778886532",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3595230/c06cc6508d956e43f97e08a6126f069364e14775/ss_c06cc6508d956e43f97e08a6126f069364e14775.1920x1080.jpg?t=1778886532",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3595230/dd05935dce85d5d334b86609f9488113fc8aad30/ss_dd05935dce85d5d334b86609f9488113fc8aad30.1920x1080.jpg?t=1778886532"
    ]
  },
  {
    "id": 2344520,
    "title": "Diablo® IV",
    "genre": "Action",
    "description": "Join the fight for Sanctuary in Diablo® IV, the ultimate action RPG adventure. Experience the critically acclaimed campaign and new seasonal content.",
    "releaseDate": "2023-10-17",
    "rating": 9.0,
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/80f21a42e378b93e8fbb68ee43103be8ab84891b/header.jpg?t=1780334052",
    "developer": "Blizzard Entertainment, Inc.",
    "platforms": ["PC"],
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/8512b560be0ddef49cb0da366b7d2ddf5df18cab/ss_8512b560be0ddef49cb0da366b7d2ddf5df18cab.1920x1080.jpg?t=1780334052",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/24952fc1c8779c9a7a555c01489c76f9814f70a7/ss_24952fc1c8779c9a7a555c01489c76f9814f70a7.1920x1080.jpg?t=1780334052",
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2344520/7eda1d661ffde2750d56517e1a46406f340675e5/ss_7eda1d661ffde2750d56517e1a46406f340675e5.1920x1080.jpg?t=1780334052"
    ]
  },
];
