#!/usr/bin/env python3
"""
Steam Game Data Fetcher
Автоматически получает реальные данные игр из Steam API
"""

import requests
import json
import time
import sys
from typing import Dict, List, Optional
from dataclasses import dataclass
from pathlib import Path


@dataclass
class GameData:
    id: int
    title: str
    genre: str
    description: str
    release_date: str
    developer: str
    header_image: str
    screenshots: List[str]
    platforms: List[str]


class SteamAPIFetcher:
    def __init__(self):
        self.base_url = "https://store.steampowered.com/api/appdetails"
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
    
    def fetch_game(self, app_id: int) -> Optional[GameData]:
        """Получает данные об игре по App ID"""
        try:
            params = {
                'appids': app_id,
                'cc': 'us',
                'l': 'english'
            }
            
            response = self.session.get(self.base_url, params=params, timeout=10)
            response.raise_for_status()
            
            data = response.json()
            
            if not data or str(app_id) not in data:
                print(f"❌ Нет данных для App ID: {app_id}")
                return None
            
            game_data = data[str(app_id)]
            
            if not game_data.get('success'):
                print(f"❌ Ошибка загрузки App ID: {app_id}")
                return None
            
            app_data = game_data['data']
            
            # Получаем скриншоты
            screenshots = []
            if 'screenshots' in app_data:
                screenshots = [
                    f"{s['path_full']}" 
                    for s in app_data['screenshots'][:3]  # Первые 3 скриншота
                ]
            
            # Определяем жанр
            genre = "Unknown"
            if 'genres' in app_data and app_data['genres']:
                genre = app_data['genres'][0].get('description', 'Unknown')
            
            # Определяем платформы
            platforms = []
            if 'platforms' in app_data:
                plat = app_data['platforms']
                if plat.get('windows'):
                    platforms.append('PC')
                if plat.get('mac'):
                    platforms.append('Mac')
                if plat.get('linux'):
                    platforms.append('Linux')
            
            if not platforms:
                platforms = ['PC']
            
            # Форматируем дату
            release_date = app_data.get('release_date', {}).get('date', 'TBA')
            if release_date == 'TBA':
                release_date = '2024-01-01'
            
            # Сокращаем описание
            description = app_data.get('short_description', '')
            if len(description) > 500:
                description = description[:497] + '...'
            
            return GameData(
                id=app_id,
                title=app_data.get('name', f'Game {app_id}'),
                genre=genre,
                description=description,
                release_date=self._format_date(release_date),
                developer=app_data.get('developers', ['Unknown Developer'])[0],
                header_image=app_data.get('header_image', ''),
                screenshots=screenshots,
                platforms=platforms
            )
            
        except requests.RequestException as e:
            print(f"❌ Ошибка сети для App ID {app_id}: {e}")
            return None
        except Exception as e:
            print(f"❌ Ошибка обработки App ID {app_id}: {e}")
            return None
    
    def _format_date(self, date_str: str) -> str:
        """Преобразует дату в формат YYYY-MM-DD"""
        try:
            # Steam использует разные форматы
            from datetime import datetime
            
            # Попробуем разные форматы
            formats = [
                '%b %d, %Y',
                '%d %b, %Y',
                '%Y-%m-%d',
                '%m/%d/%Y',
                '%d/%m/%Y'
            ]
            
            for fmt in formats:
                try:
                    return datetime.strptime(date_str.strip(), fmt).strftime('%Y-%m-%d')
                except ValueError:
                    continue
            
            return '2024-01-01'
        except:
            return '2024-01-01'
    
    def generate_dart_code(self, games: List[GameData]) -> str:
        """Генерирует Dart код для games_data_steam.dart"""
        
        dart_code = '''// Steam Game Data with real screenshots from Steam API
// Auto-generated by fetch_steam_data.py

const List<Map<String, dynamic>> gamesSteamData = [
'''
        
        for game in games:
            if game is None:
                continue
                
            # Escape quotes in description
            description = game.description.replace('"', '\\"').replace('\n', ' ')
            
            # Build screenshots array
            screenshots_str = ',\n      '.join([f'"{s}"' for s in game.screenshots])
            
            dart_code += f'''  {{
    "id": {game.id},
    "title": "{game.title}",
    "genre": "{game.genre}",
    "description": "{description}",
    "releaseDate": "{game.release_date}",
    "rating": 9.0,
    "imageUrl": "{game.header_image}",
    "developer": "{game.developer}",
    "platforms": {json.dumps(game.platforms)},
    "status": "Released",
    "isFree": false,
    "trailerUrl": "",
    "screenshots": [
      {screenshots_str}
    ]
  }},
'''
        
        dart_code += '];\n'
        return dart_code


def main():
    # Популярные игры Steam с их App ID
    game_ids = [
        292030,    # The Witcher 3
        1091500,   # Cyberpunk 2077
        271590,    # GTA V
        1174180,   # Red Dead Redemption 2
        1245620,   # Elden Ring
        1593500,   # God of War
        1151640,   # Horizon Zero Dawn
        990080,    # Hogwarts Legacy
        1086940,   # Baldur's Gate 3
        1817070,   # Spider-Man Remastered
        2050650,   # Resident Evil 4
        1364780,   # Street Fighter 6
        1938090,   # Call of Duty MW2
        1693980,   # Dead Space
        1716740,   # Starfield
        1426210,   # It Takes Two
        1145360,   # Hades
        413150,    # Stardew Valley
        367520,    # Hollow Knight
        1172470,   # Apex Legends
        1885730,   # The Last of Us Part I
        1659040,   # Marvel's Spider-Man Miles Morales
        1971650,   # Star Wars Jedi: Survivor
        1962660,   # Call of Duty MW3
        2344520,   # Diablo IV
    ]
    
    fetcher = SteamAPIFetcher()
    games = []
    
    print("🎮 Начинаем загрузку данных из Steam API...")
    print(f"📋 Всего игр в очереди: {len(game_ids)}\n")
    
    for i, app_id in enumerate(game_ids, 1):
        print(f"[{i}/{len(game_ids)}] Загрузка App ID: {app_id}...", end=' ')
        
        game = fetcher.fetch_game(app_id)
        if game:
            games.append(game)
            print(f"✅ {game.title[:40]}...")
        else:
            print("❌ Пропущено")
        
        # Задержка чтобы не перегружать API
        time.sleep(1.5)
    
    print(f"\n✅ Успешно загружено: {len(games)} из {len(game_ids)} игр")
    
    if games:
        # Генерируем Dart код
        dart_code = fetcher.generate_dart_code(games)
        
        # Сохраняем в файл
        output_path = Path(__file__).parent.parent / 'lib' / 'data' / 'games_data_steam_auto.dart'
        output_path.write_text(dart_code, encoding='utf-8')
        
        print(f"\n💾 Dart файл сохранён: {output_path}")
        print(f"📊 Итоговая статистика:")
        print(f"   - Игр: {len(games)}")
        print(f"   - Скриншотов: {sum(len(g.screenshots) for g in games)}")
        
        # Показываем список загруженных игр
        print(f"\n📋 Загруженные игры:")
        for game in games:
            print(f"   ✓ {game.title}")
            print(f"     Скриншотов: {len(game.screenshots)}")
    else:
        print("\n❌ Ни одна игра не была загружена")
        sys.exit(1)


if __name__ == "__main__":
    main()
